-- ============================================================
-- INSERT INTO common_terms
-- IDs a partir de 11 (1-10 já existem)
-- ============================================================

INSERT INTO public.common_terms (id, code, name_pt, category) VALUES

-- Geral / UI
(11,  'ui.loading',              'Carregando...',                    'Geral'),
(12,  'ui.loading_dashboard',    'Carregando dashboard…',            'Geral'),
(13,  'ui.back',                 'Voltar',                           'Geral'),
(14,  'ui.try_again',            'Tentar novamente',                 'Geral'),
(15,  'ui.all_countries',        'Todos os países',                  'Geral'),
(16,  'ui.explore_by_country',   'Explorar por país',                'Geral'),
(17,  'ui.clear_all',            'Limpar tudo',                      'Geral'),
(18,  'ui.clear_filters',        'Limpar filtros',                   'Geral'),
(19,  'ui.clear_search',         'Limpar busca',                     'Geral'),
(20,  'ui.save_changes',         'Salvar alterações',                'Geral'),
(21,  'ui.select',               'Selecione',                        'Geral'),
(22,  'ui.all',                  'Todos',                            'Geral'),
(23,  'ui.unavailable',          'Indisponível',                     'Geral'),
(24,  'ui.see_more',             'Ver mais',                         'Geral'),
(25,  'ui.item',                 'Item',                             'Geral'),
(26,  'ui.value',                'Valor',                            'Geral'),
(27,  'ui.status',               'Status',                           'Geral'),

-- Ligas
(28,  'leagues.search_placeholder',   'Buscar liga…',                              'Ligas'),
(29,  'leagues.singular',             'liga',                                      'Ligas'),
(30,  'leagues.plural',               'ligas',                                     'Ligas'),
(31,  'leagues.not_found',            'Nenhuma liga encontrada',                   'Ligas'),
(32,  'leagues.try_other_terms',      'Tente outros termos ou limpe os filtros',   'Ligas'),
(33,  'leagues.compare_placeholder',  'Comparar liga…',                            'Ligas'),
(34,  'leagues.searching',            'Buscando ligas...',                         'Ligas'),
(35,  'leagues.limit_reached',        'Limite atingido',                           'Ligas'),
(36,  'leagues.none_registered',      'Nenhuma liga cadastrada para este país.',   'Ligas'),

-- Clubes
(37,  'clubs.search_placeholder',   'Buscar clube…',                             'Clubes'),
(38,  'clubs.singular',             'clube',                                     'Clubes'),
(39,  'clubs.plural',               'clubes',                                    'Clubes'),
(40,  'clubs.not_found',            'Nenhum clube encontrado',                   'Clubes'),
(41,  'clubs.not_found_period',     'Nenhum clube encontrado.',                  'Clubes'),
(42,  'clubs.try_other_terms',      'Tente outros termos ou limpe os filtros',   'Clubes'),
(43,  'clubs.compare_placeholder',  'Comparar clube…',                           'Clubes'),
(44,  'clubs.searching',            'Buscando clubes...',                        'Clubes'),
(45,  'clubs.foundation',           'Fundação',                                  'Clubes'),
(46,  'clubs.stadium',              'Estádio',                                   'Clubes'),
(47,  'clubs.corporate_structure',  'Estrutura empresarial',                     'Clubes'),
(48,  'clubs.finances',             'Finanças',                                  'Clubes'),
(49,  'clubs.sports_results',       'Resultados esportivos',                     'Clubes'),
(50,  'clubs.main_squad',           'Elenco principal',                          'Clubes'),

-- Países
(51,  'countries.title',              'Países',                                   'Países'),
(52,  'countries.subtitle',           'países com ligas ou clubes cadastrados',   'Países'),
(53,  'countries.search_placeholder', 'Buscar país...',                           'Países'),
(54,  'countries.not_found',          'Nenhum país encontrado',                   'Países'),
(55,  'countries.try_search',         'Tente ajustar a busca.',                   'Países'),
(56,  'countries.filter_club',        'Filtrar clube...',                         'Países'),

-- Jogadores (lista)
(57,  'players.search_placeholder',  'Buscar por nome...',                                   'Jogadores'),
(58,  'players.singular',            'jogador',                                              'Jogadores'),
(59,  'players.plural',              'jogadores',                                            'Jogadores'),
(60,  'players.not_found',           'Nenhum jogador encontrado',                            'Jogadores'),
(61,  'players.try_filters',         'Tente ajustar os filtros ou o nome buscado.',          'Jogadores'),
(62,  'players.none_registered',     'Ainda não há jogadores cadastrados.',                  'Jogadores'),
(63,  'players.loaded_count',        'jogadores carregados',                                 'Jogadores'),
(64,  'players.loading_squad',       'Carregando elenco...',                                 'Jogadores'),
(65,  'players.none_in_season',      'Nenhum jogador encontrado para a temporada',           'Jogadores'),
(66,  'players.select_season',       'Selecione a temporada',                                'Jogadores'),
(67,  'players.age_suffix',          'anos',                                                 'Jogadores'),

-- Posições de jogadores
(68,  'players.position.goalkeeper',   'Goleiro',           'Jogadores'),
(69,  'players.position.fullback',     'Lateral',           'Jogadores'),
(70,  'players.position.defender',     'Zagueiro',          'Jogadores'),
(71,  'players.position.midfielder',   'Meio-campista',     'Jogadores'),
(72,  'players.position.forward',      'Atacante',          'Jogadores'),
(73,  'players.position.goalkeepers',  'Goleiros',          'Jogadores'),
(74,  'players.position.fullbacks',    'Laterais',          'Jogadores'),
(75,  'players.position.defenders',    'Zagueiros',         'Jogadores'),
(76,  'players.position.midfielders',  'Meio campistas',    'Jogadores'),
(77,  'players.position.forwards',     'Atacantes',         'Jogadores'),

-- Perfil de jogador (stats)
(78,  'player.loading',                 'Carregando jogador...',      'Jogadores'),
(79,  'player.tab.participation',       'Participação',               'Jogadores'),
(80,  'player.tab.offensive',           'Ofensivo',                   'Jogadores'),
(81,  'player.tab.shots',               'Chutes',                     'Jogadores'),
(82,  'player.tab.technical',           'Técnico',                    'Jogadores'),
(83,  'player.tab.disciplinary',        'Disciplinar',                'Jogadores'),
(84,  'player.stat.position',           'Posição',                    'Jogadores'),
(85,  'player.stat.birth',              'Nascimento',                 'Jogadores'),
(86,  'player.stat.nationality',        'Nacionalidade',              'Jogadores'),
(87,  'player.stat.matches',            'Partidas',                   'Jogadores'),
(88,  'player.stat.minutes',            'Minutos',                    'Jogadores'),
(89,  'player.stat.goals',              'Gols',                       'Jogadores'),
(90,  'player.stat.assists_short',      'Assist.',                    'Jogadores'),
(91,  'player.stat.yellow_short',       'Amarelos',                   'Jogadores'),
(92,  'player.stat.rating',             'Rating',                     'Jogadores'),
(93,  'player.stat.total_matches',      'Partidas total',             'Jogadores'),
(94,  'player.stat.as_starter',         'Como titular',               'Jogadores'),
(95,  'player.stat.total_minutes',      'Minutos total',              'Jogadores'),
(96,  'player.stat.avg_rating',         'Rating médio',               'Jogadores'),
(97,  'player.stat.minutes_played',     'Minutos jogados',            'Jogadores'),
(98,  'player.stat.minutes_per_game',   'Minutos por jogo',           'Jogadores'),
(99,  'player.stat.starter_matches',    'Partidas como titular',      'Jogadores'),
(100, 'player.stat.club',               'Clube',                      'Jogadores'),
(101, 'player.stat.league',             'Liga',                       'Jogadores'),
(102, 'player.stat.jersey',             'Camisa',                     'Jogadores'),
(103, 'player.stat.market_value',       'Valor de mercado',           'Jogadores'),
(104, 'player.stat.assists',            'Assistências',               'Jogadores'),
(105, 'player.stat.xg_total',           'xG total',                   'Jogadores'),
(106, 'player.stat.penalties',          'Pênaltis',                   'Jogadores'),
(107, 'player.stat.clean_sheets',       'Clean sheets',               'Jogadores'),
(108, 'player.stat.penalties_scored',   'Pênaltis marcados',          'Jogadores'),
(109, 'player.stat.penalties_missed',   'Pênaltis perdidos',          'Jogadores'),
(110, 'player.stat.offsides',           'Impedimentos',               'Jogadores'),
(111, 'player.stat.total_shots',        'Chutes totais',              'Jogadores'),
(112, 'player.stat.shots_per_game',     'Chutes por jogo',            'Jogadores'),
(113, 'player.stat.on_target_short',    'A gol',                      'Jogadores'),
(114, 'player.stat.on_target',          'Chutes a gol',               'Jogadores'),
(115, 'player.stat.on_target_per_game', 'Chutes a gol por jogo',      'Jogadores'),
(116, 'player.stat.shot_accuracy',      'Precisão de chute',          'Jogadores'),
(117, 'player.stat.accuracy_short',     'Precisão',                   'Jogadores'),
(118, 'player.stat.passes',             'Passes',                     'Jogadores'),
(119, 'player.stat.pass_accuracy_short','Acerto passes',              'Jogadores'),
(120, 'player.stat.passes_correct',     'Passes certos',              'Jogadores'),
(121, 'player.stat.pass_rate',          'Taxa de acerto',             'Jogadores'),
(122, 'player.stat.short_passes',       'Passes curtos',              'Jogadores'),
(123, 'player.stat.long_passes',        'Passes longos',              'Jogadores'),
(124, 'player.stat.key_passes',         'Passes-chave',               'Jogadores'),
(125, 'player.stat.tackles',            'Desarmes',                   'Jogadores'),
(126, 'player.stat.interceptions',      'Interceptações',             'Jogadores'),
(127, 'player.stat.crosses',            'Cruzamentos',                'Jogadores'),
(128, 'player.stat.dribbles_attempted', 'Dribles tentados',           'Jogadores'),
(129, 'player.stat.dribbles_success',   'Dribles bem-sucedidos',      'Jogadores'),
(130, 'player.stat.total_duels',        'Duelos totais',              'Jogadores'),
(131, 'player.stat.duels_won',          'Duelos vencidos %',          'Jogadores'),
(132, 'player.stat.saves',              'Defesas',                    'Jogadores'),
(133, 'player.stat.saves_inside',       'Defesas dentro da área',     'Jogadores'),
(134, 'player.stat.yellow_cards',       'Cartões amarelos',           'Jogadores'),
(135, 'player.stat.red_cards',          'Cartões vermelhos',          'Jogadores'),
(136, 'player.stat.fouls',              'Faltas cometidas',           'Jogadores'),
(137, 'player.stat.fouls_per_game',     'Faltas por jogo',            'Jogadores'),

-- Esportivo (seções ligas & clubes)
(138, 'sports.tab',                  'Esportivo',                              'Esportivo'),
(139, 'sports.classification',       'Classificação',                          'Esportivo'),
(140, 'sports.matches',              'Partidas',                               'Esportivo'),
(141, 'sports.round',                'Rodada',                                 'Esportivo'),
(142, 'sports.no_round',             'Sem rodada',                             'Esportivo'),
(143, 'sports.no_round_defined',     'Sem rodada definida',                    'Esportivo'),
(144, 'sports.season',               'Temporada',                              'Esportivo'),
(145, 'sports.round_robin',          'Pontos corridos',                        'Esportivo'),
(146, 'sports.knockout',             'Mata-mata',                              'Esportivo'),
(147, 'sports.position',             'Posição',                                'Esportivo'),
(148, 'sports.points',               'Pontos',                                 'Esportivo'),
(149, 'sports.wins',                 'Vitórias',                               'Esportivo'),
(150, 'sports.draws',                'Empates',                                'Esportivo'),
(151, 'sports.losses',               'Derrotas',                               'Esportivo'),
(152, 'sports.goals_for',            'Gols pró',                               'Esportivo'),
(153, 'sports.goals_against',        'Gols contra',                            'Esportivo'),
(154, 'sports.total',                'Total',                                  'Esportivo'),
(155, 'sports.home',                 'Casa',                                   'Esportivo'),
(156, 'sports.away',                 'Fora',                                   'Esportivo'),
(157, 'sports.games_suffix',         'jogos',                                  'Esportivo'),
(158, 'sports.no_matches',           'Nenhuma partida registrada.',            'Esportivo'),
(159, 'sports.no_classification',    'Sem dados de classificação.',            'Esportivo'),
(160, 'sports.no_data_season',       'Nenhum dado para a temporada',           'Esportivo'),
(161, 'sports.goals_scored',         'Gols marcados',                          'Esportivo'),
(162, 'sports.goals_conceded',       'Gols sofridos',                          'Esportivo'),
(163, 'sports.shots',                'Chutes',                                 'Esportivo'),
(164, 'sports.avg_possession',       'Posse média',                            'Esportivo'),
(165, 'sports.stat_label',           'Estatística',                            'Esportivo'),
(166, 'sports.shots_on_target',      'Chutes a gol',                           'Esportivo'),
(167, 'sports.possession',           'Posse de bola',                          'Esportivo'),
(168, 'sports.clean_sheets',         'Clean sheets',                           'Esportivo'),
(169, 'sports.corners',              'Escanteios',                             'Esportivo'),
(170, 'sports.goals_per_game',       'Gols marcados por jogo',                 'Esportivo'),
(171, 'sports.goals_conceded_pg',    'Gols sofridos por jogo',                 'Esportivo'),
(172, 'sports.xg_avg_pro',           'xG médio (pró)',                         'Esportivo'),
(173, 'sports.xg_avg_against',       'xG médio (contra)',                      'Esportivo'),
(174, 'sports.btts_pct',             'Ambos marcam %',                         'Esportivo'),
(175, 'sports.over25_pct',           'Acima de 2.5 gols %',                    'Esportivo'),
(176, 'sports.clean_sheet_pct',      'Clean sheet %',                          'Esportivo'),
(177, 'sports.points_per_game',      'Pontos por jogo',                        'Esportivo'),
(178, 'sports.winning_ht',           'Vencendo no intervalo',                  'Esportivo'),
(179, 'sports.drawing_ht',           'Empatando',                              'Esportivo'),
(180, 'sports.losing_ht',            'Perdendo',                               'Esportivo'),
(181, 'sports.drawing_interval',     'Empatando no intervalo',                 'Esportivo'),
(182, 'sports.losing_interval',      'Perdendo no intervalo',                  'Esportivo'),
(183, 'sports.goals_scored_1h',      'Gols marcados (1º tempo)',               'Esportivo'),
(184, 'sports.goals_conceded_1h',    'Gols sofridos (1º tempo)',               'Esportivo'),
(185, 'sports.yellow_cards',         'Cartões amarelos',                       'Esportivo'),
(186, 'sports.red_cards',            'Cartões vermelhos',                      'Esportivo'),
(187, 'sports.fouls',                'Faltas',                                 'Esportivo'),
(188, 'sports.fouls_committed',      'Faltas cometidas',                       'Esportivo'),
(189, 'sports.fouls_per_game',       'Faltas por jogo',                        'Esportivo'),
(190, 'sports.clubs_around',         'clubes · exibindo posições ao redor do seu clube', 'Esportivo'),
(191, 'sports.place_suffix',         'º lugar',                                'Esportivo'),
(192, 'sports.interval_tab',         'Intervalo',                              'Esportivo'),

-- Notas
(193, 'notes.title',          'Notas',                                  'Notas'),
(194, 'notes.subtitle',       'Análises e conteúdos exclusivos',        'Notas'),
(195, 'notes.singular',       'nota',                                   'Notas'),
(196, 'notes.plural',         'notas',                                  'Notas'),
(197, 'notes.access',         'Acessar nota',                           'Notas'),
(198, 'notes.label',          'Nota',                                   'Notas'),
(199, 'notes.none_available', 'Nenhuma nota disponível no momento.',    'Notas'),
(200, 'notes.see_more',       'Ver mais notas',                         'Notas'),

-- Relatórios
(201, 'reports.title',          'Relatórios',                                                    'Relatórios'),
(202, 'reports.subtitle',       'Análises e documentos exclusivos disponíveis para download',    'Relatórios'),
(203, 'reports.singular',       'relatório',                                                     'Relatórios'),
(204, 'reports.download_pdf',   'Baixar PDF',                                                    'Relatórios'),
(205, 'reports.pdf_label',      'PDF',                                                           'Relatórios'),
(206, 'reports.none_available', 'Nenhum relatório disponível no momento.',                       'Relatórios'),
(207, 'reports.see_more',       'Ver mais relatórios',                                           'Relatórios'),

-- Perfil
(208, 'profile.title',                 'Meu perfil',                                                                                   'Perfil'),
(209, 'profile.personal_data_title',   'Dados Pessoais',                                                                               'Perfil'),
(210, 'profile.personal_data_subtitle','Mantenha suas informações atualizadas.',                                                        'Perfil'),
(211, 'profile.photo',                 'Foto de perfil',                                                                               'Perfil'),
(212, 'profile.photo_recommendation',  'Recomendado: PNG ou JPG.',                                                                     'Perfil'),
(213, 'profile.change_photo',          'Alterar foto',                                                                                 'Perfil'),
(214, 'profile.full_name',             'Nome completo',                                                                                'Perfil'),
(215, 'profile.name_placeholder',      'Seu nome',                                                                                     'Perfil'),
(216, 'profile.email',                 'E-mail',                                                                                       'Perfil'),
(217, 'profile.email_placeholder',     'seu@email.com',                                                                                'Perfil'),
(218, 'profile.google_email_note',     'Sua conta está conectada com o Google. O e-mail não pode ser alterado por aqui.',              'Perfil'),
(219, 'profile.google_email_support',  'Entre em contato com o suporte para alterar seu e-mail',                                       'Perfil'),
(220, 'profile.success',               'Perfil atualizado com sucesso!',                                                               'Perfil'),
(221, 'profile.security_title',        'Segurança',                                                                                    'Perfil'),
(222, 'profile.security_subtitle',     'Atualize sua senha de acesso.',                                                                'Perfil'),
(223, 'profile.google_managed',        'Gerenciado pelo Google',                                                                       'Perfil'),
(224, 'profile.google_password_note',  'Como você fez login via Google, a alteração de senha deve ser feita diretamente na sua conta Google.', 'Perfil'),
(225, 'profile.current_password',      'Senha atual',                                                                                  'Perfil'),
(226, 'profile.password_placeholder',  '••••••••',                                                                                     'Perfil'),
(227, 'profile.new_password',          'Nova senha',                                                                                   'Perfil'),
(228, 'profile.password_min',          'Mínimo de 8 caracteres.',                                                                      'Perfil'),
(229, 'profile.password_success',      'Senha atualizada com sucesso!',                                                                'Perfil'),
(230, 'profile.change_password',       'Alterar senha',                                                                                'Perfil'),

-- Validação
(231, 'validation.fill_password_fields',  'Por favor, preencha a senha atual e a nova senha.',    'Validação'),
(232, 'validation.password_min_length',   'A nova senha deve ter pelo menos 8 caracteres.',       'Validação'),
(233, 'validation.current_password_wrong','A senha atual está incorreta.',                         'Validação'),
(234, 'validation.fill_name_email',       'Por favor, preencha o nome e o e-mail.',               'Validação'),
(235, 'validation.name_required',         'O nome é obrigatório.',                                'Validação'),
(236, 'validation.name_min',              'O nome deve ter pelo menos 3 caracteres.',             'Validação'),
(237, 'validation.email_required',        'O e-mail é obrigatório.',                              'Validação'),

-- Financeiro (perfil do usuário)
(238, 'financial.title',               'Assinatura e Cobrança',                                                          'Financeiro Perfil'),
(239, 'financial.subtitle',            'Gerencie seu plano, métodos de pagamento e notas fiscais.',                      'Financeiro Perfil'),
(240, 'financial.upgrade',             'Fazer Upgrade',                                                                  'Financeiro Perfil'),
(241, 'financial.change_plan',         'Mudar Plano',                                                                    'Financeiro Perfil'),
(242, 'financial.reactivate',          'Reativar assinatura',                                                            'Financeiro Perfil'),
(243, 'financial.loading',             'Carregando seu plano...',                                                        'Financeiro Perfil'),
(244, 'financial.free_plan',           'Plano Gratuito',                                                                 'Financeiro Perfil'),
(245, 'financial.free',                'Grátis',                                                                         'Financeiro Perfil'),
(246, 'financial.upgrade_premium',     'Faça upgrade para desbloquear recursos premium',                                 'Financeiro Perfil'),
(247, 'financial.access_until',        'Acesso garantido até',                                                           'Financeiro Perfil'),
(248, 'financial.subscription_via',    'Assinatura ativa via',                                                           'Financeiro Perfil'),
(249, 'financial.see_plans',           'Ver planos disponíveis',                                                         'Financeiro Perfil'),
(250, 'financial.alter_plan',          'Alterar Plano',                                                                  'Financeiro Perfil'),
(251, 'financial.cancel',              'Cancelar Assinatura',                                                            'Financeiro Perfil'),
(252, 'financial.support_title',       'Suporte Financeiro',                                                             'Financeiro Perfil'),
(253, 'financial.support_subtitle',    'Dúvidas sobre faturas ou mudança de plano?',                                     'Financeiro Perfil'),
(254, 'financial.contact_support',     'Falar com suporte',                                                              'Financeiro Perfil'),
(255, 'financial.status_active',       'Ativo',                                                                          'Financeiro Perfil'),
(256, 'financial.status_free',         'Gratuito',                                                                       'Financeiro Perfil'),
(257, 'financial.status_cancel_sched', 'Cancelamento agendado',                                                          'Financeiro Perfil'),
(258, 'financial.status_cancelled',    'Cancelado',                                                                      'Financeiro Perfil'),
(259, 'financial.expires_on',          'Expira em',                                                                      'Financeiro Perfil'),
(260, 'financial.unlock_premium',      'Desbloqueie o Premium',                                                          'Financeiro Perfil'),
(261, 'financial.premium_subtitle',    'Acesse recursos avançados e suporte prioritário.',                               'Financeiro Perfil'),
(262, 'financial.cancel_title',        'Cancelar Assinatura?',                                                           'Financeiro Perfil'),
(263, 'financial.cancel_text',         'Tem certeza que deseja cancelar o',                                              'Financeiro Perfil'),
(264, 'financial.cancel_lose_access',  'Você perderá acesso a todos os recursos premium ao final do ciclo atual.',       'Financeiro Perfil'),
(265, 'financial.cancel_stripe_note',  'Você será redirecionado para o portal seguro do Stripe para confirmar o cancelamento.', 'Financeiro Perfil'),
(266, 'financial.keep_plan',           'Não, manter meu plano',                                                          'Financeiro Perfil'),
(267, 'financial.go_to_cancel',        'Ir para o portal de cancelamento',                                               'Financeiro Perfil'),
(268, 'financial.my_plan',             'Seu Plano',                                                                      'Financeiro Perfil'),

-- Assinatura
(269, 'subscription.title',           'Minha assinatura',                                                              'Assinatura'),
(270, 'subscription.subtitle',        'Gerencie sua assinatura e veja o histórico de pagamentos.',                     'Assinatura'),
(271, 'subscription.basic',           'Plano básico',                                                                  'Assinatura'),
(272, 'subscription.basic_desc',      'Você está utilizando o plano básico.',                                          'Assinatura'),
(273, 'subscription.limited_access',  'Acesso limitado',                                                               'Assinatura'),
(274, 'subscription.no_history',      'Sem histórico de pagamentos',                                                   'Assinatura'),
(275, 'subscription.update',          'Atualizar assinatura',                                                          'Assinatura'),
(276, 'subscription.active',          'Assinatura ativa',                                                              'Assinatura'),
(277, 'subscription.free',            'Grátis',                                                                        'Assinatura'),
(278, 'subscription.premium',         'Premium',                                                                       'Assinatura'),
(279, 'subscription.business',        'Business',                                                                      'Assinatura'),
(280, 'subscription.status_active',   'Ativo',                                                                         'Assinatura'),
(281, 'subscription.status_cancelled','Cancelado',                                                                      'Assinatura'),
(282, 'subscription.status_pending',  'Pendente',                                                                      'Assinatura'),
(283, 'subscription.next_payment',    'Próximo pagamento:',                                                            'Assinatura'),
(284, 'subscription.cancel_notice',   'Sua assinatura será cancelada ao final do período de faturamento atual.',       'Assinatura'),
(285, 'subscription.view_invoices',   'Ver faturas',                                                                   'Assinatura'),

-- Contato
(286, 'contact.culture_title',             'Nossa Cultura',                                          'Contato'),
(287, 'contact.culture_subtitle',          'Conectando apaixonados por esporte em todo o mundo.',   'Contato'),
(288, 'contact.follow_us',                 'Siga-nos',                                              'Contato'),
(289, 'contact.whatsapp',                  'WhatsApp',                                              'Contato'),
(290, 'contact.whatsapp_hours',            'Seg-Sex das 9h às 18h',                                 'Contato'),
(291, 'contact.whatsapp_number',           '+55 (11) 96629-5142',                                   'Contato'),
(292, 'contact.email_label',               'E-mail',                                                'Contato'),
(293, 'contact.email_response',            'Resposta em até 24h',                                   'Contato'),
(294, 'contact.email_address',             'suporte@sportinsider.com',                              'Contato'),
(295, 'contact.title',                     'Fale Conosco',                                          'Contato'),
(296, 'contact.subtitle',                  'Preencha o formulário e entraremos em contato.',        'Contato'),
(297, 'contact.name',                      'Nome',                                                  'Contato'),
(298, 'contact.name_placeholder',          'Seu nome',                                              'Contato'),
(299, 'contact.last_name',                 'Sobrenome',                                             'Contato'),
(300, 'contact.corporate_email',           'E-mail Corporativo',                                    'Contato'),
(301, 'contact.corporate_email_placeholder','voce@empresa.com',                                     'Contato'),
(302, 'contact.phone',                     'Telefone',                                              'Contato'),
(303, 'contact.phone_placeholder',         '+55 (11) 99999-0000',                                   'Contato'),
(304, 'contact.message',                   'Como podemos ajudar?',                                  'Contato'),
(305, 'contact.message_placeholder',       'Conte-nos sobre seu projeto ou dúvida...',              'Contato'),
(306, 'contact.sending',                   'Enviando...',                                           'Contato'),
(307, 'contact.send',                      'Enviar Mensagem',                                       'Contato'),
(308, 'contact.privacy',                   'Política de Privacidade',                               'Contato'),
(309, 'contact.success_title',             'Mensagem Recebida!',                                    'Contato'),
(310, 'contact.success_thanks',            'Obrigado,',                                             'Contato'),
(311, 'contact.success_text',              'Nossa equipe comercial entrará em contato em breve.',   'Contato'),
(312, 'contact.send_another',              'Enviar outra mensagem',                                 'Contato'),

-- FAQ
(313, 'faq.title',              'Perguntas Frequentes',                                       'FAQ'),
(314, 'faq.subtitle',           'Tire suas dúvidas sobre a plataforma e funcionalidades.',   'FAQ'),
(315, 'faq.search_placeholder', 'Buscar uma dúvida...',                                      'FAQ'),
(316, 'faq.general_doubts',     'Dúvidas Gerais',                                            'FAQ'),
(317, 'faq.not_found',          'Nenhuma dúvida encontrada para',                            'FAQ'),
(318, 'faq.need_help',          'Ainda precisa de ajuda?',                                   'FAQ'),
(319, 'faq.support_text',       'Nossa equipe de suporte responde em até 24h.',              'FAQ'),
(320, 'faq.contact_support',    'Falar com suporte',                                         'FAQ'),

-- Preferências
(321, 'preferences.title',               'Preferências',                         'Preferências'),
(322, 'preferences.subtitle',            'Personalize notificações, região e moeda.', 'Preferências'),
(323, 'preferences.not_found',           'Preferências não encontradas.',         'Preferências'),
(324, 'preferences.success',             'Preferências atualizadas com sucesso!', 'Preferências'),
(325, 'preferences.notifications',       'Notificações',                          'Preferências'),
(326, 'preferences.email_notifications', 'Notificações por e-mail',               'Preferências'),
(327, 'preferences.product_updates',     'Atualizações de Produto',               'Preferências'),
(328, 'preferences.region_currency',     'Região e moeda',                        'Preferências'),
(329, 'preferences.region',              'Região',                                'Preferências'),
(330, 'preferences.currency',            'Moeda',                                 'Preferências'),
(331, 'preferences.save',                'Salvar preferências',                   'Preferências'),

-- Privacidade / Deletar conta
(332, 'privacy.confirm_title',     'Você tem certeza disso?',                                                                                                             'Privacidade'),
(333, 'privacy.irreversible',      'As ações realizadas aqui são irreversíveis.',                                                                                         'Privacidade'),
(334, 'privacy.delete_title',      'Deletar conta permanentemente',                                                                                                       'Privacidade'),
(335, 'privacy.delete_description','Ao deletar sua conta, todos os seus dados, histórico de assinaturas e preferências serão removidos permanentemente dos nossos servidores.', 'Privacidade'),
(336, 'privacy.cannot_undo',       'Essa ação não pode ser desfeita.',                                                                                                    'Privacidade'),
(337, 'privacy.type_to_confirm',   'Para confirmar, digite',                                                                                                              'Privacidade'),
(338, 'privacy.below',             'abaixo:',                                                                                                                             'Privacidade'),
(339, 'privacy.delete_button',     'Deletar minha conta',                                                                                                                 'Privacidade'),

-- Plano / Upgrade
(340, 'plan.available_pro_premium', 'Disponível nos planos Pro e Premium', 'Planos'),

-- Dashboard principal
(341, 'dashboard.greeting', 'Olá', 'Dashboard');
